name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go/@v3
        with:
          go-version: 1.19

      - name: Install Dependencies
        run: go mod tidy && go mod vendor

      - name: Test
        run: go test -v ./...

  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go/@v3
        with:
          go-version: 1.19

      - name: Install Dependencies
        run: go mod tidy && go mod vendor

      - name: Install gosec
        run: curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest

      - name: SAST
        run: gosec -fmt=html -out=.public/sast/index.html ./...; gosec -fmt=json -out=.public/sast/results.json ./...; gosec ./...

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go/@v3
        with:
          go-version: 1.19

      - name: Install Dependencies
        run: go mod download && go mod verify

      - name: Build
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/

  # TODO: release:
